# Generated by Django 5.0.4 on 2026-04-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sNo', models.CharField(blank=True, max_length=50, null=True)),
                ('ipAddress', models.CharField(blank=True, max_length=45, null=True)),
                ('nvrName', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('hardDisk', models.CharField(blank=True, max_length=100, null=True)),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('serialNumber', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
