# Generated by Django 5.0.4 on 2026-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0002_nvr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(default='Boom Barrier', max_length=100)),
                ('gateStatus', models.CharField(default='Closed', max_length=50)),
                ('controller', models.CharField(blank=True, max_length=100, null=True)),
                ('lastUsed', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Biometric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(default='Fingerprint', max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('ipAddress', models.CharField(blank=True, max_length=45, null=True)),
                ('syncStatus', models.CharField(default='In Sync', max_length=100)),
                ('lastCheckIn', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
