# Generated by Django 5.0.4 on 2026-04-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0004_camera_block_camera_devicetype_camera_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='campusZone',
            field=models.CharField(choices=[('INSIDE', 'Inside Campus'), ('OUTSIDE', 'Outside Campus')], default='INSIDE', max_length=10),
        ),
    ]
