# Generated by Django 5.0.4 on 2026-05-02 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_camera_campuszone'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSwitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ipAddress', models.CharField(blank=True, max_length=45, null=True)),
                ('location', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('portCount', models.CharField(blank=True, max_length=50, null=True)),
                ('serialNumber', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance')], default='Online', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
