# Generated by Django 5.0.4 on 2026-05-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0007_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
