# Generated by Django 5.0.4 on 2026-05-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0011_biometricremark_switchremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricremark',
            name='device_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cameraremark',
            name='device_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='nvrremark',
            name='device_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='switchremark',
            name='device_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
