# Generated by Django 5.0.4 on 2026-05-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0012_biometricremark_device_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nvr',
            old_name='company',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='camera',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
