# Generated by Django 5.0.4 on 2026-05-04 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0013_rename_company_nvr_brand_camera_brand'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_location', models.CharField(max_length=255)),
                ('new_location', models.CharField(max_length=255)),
                ('old_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('new_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('biometric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='cctv.biometric')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CameraRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_location', models.CharField(max_length=255)),
                ('new_location', models.CharField(max_length=255)),
                ('old_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('new_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='cctv.camera')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NVRRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_location', models.CharField(max_length=255)),
                ('new_location', models.CharField(max_length=255)),
                ('old_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('new_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('nvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='cctv.nvr')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SwitchRelocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_location', models.CharField(max_length=255)),
                ('new_location', models.CharField(max_length=255)),
                ('old_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('new_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('switch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relocations', to='cctv.networkswitch')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
