# Generated by Django 5.0.4 on 2026-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0014_biometricrelocation_camerarelocation_nvrrelocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometric',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nvr',
            name='serialNumber',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
