# Generated by Django 5.0.4 on 2026-05-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0015_biometric_serialnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='collegeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
