# Generated by Django 5.0.4 on 2026-05-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0016_camera_collegename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='cameraId',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
