# Generated by Django 5.0.4 on 2026-05-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0017_alter_camera_cameraid'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
