# Generated by Django 5.0.4 on 2026-05-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0018_camera_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='campusZone',
            field=models.CharField(choices=[('INSIDE', 'Inside Campus'), ('OUTSIDE', 'Outside Campus')], default='INSIDE', max_length=10),
        ),
        migrations.AddField(
            model_name='barrier',
            name='collegeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barrier',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biometric',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biometric',
            name='campusZone',
            field=models.CharField(choices=[('INSIDE', 'Inside Campus'), ('OUTSIDE', 'Outside Campus')], default='INSIDE', max_length=10),
        ),
        migrations.AddField(
            model_name='biometric',
            name='collegeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biometric',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='biometric',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='campusZone',
            field=models.CharField(choices=[('INSIDE', 'Inside Campus'), ('OUTSIDE', 'Outside Campus')], default='INSIDE', max_length=10),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='collegeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='campusZone',
            field=models.CharField(choices=[('INSIDE', 'Inside Campus'), ('OUTSIDE', 'Outside Campus')], default='INSIDE', max_length=10),
        ),
        migrations.AddField(
            model_name='nvr',
            name='collegeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
