# Generated by Django 6.0.5 on 2026-05-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0019_barrier_block_barrier_campuszone_barrier_collegename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegeName', models.CharField(blank=True, max_length=255, null=True)),
                ('block', models.CharField(blank=True, max_length=255, null=True)),
                ('floor', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
