# Generated by Django 6.0.5 on 2026-05-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0021_masterlocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='remarks',
        ),
        migrations.AddField(
            model_name='globalsiteconfig',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterlocation',
            name='brand',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
