# Generated by Django 5.0.4 on 2026-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0022_remove_camera_remarks_globalsiteconfig_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometric',
            name='serverIp',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
