# Generated by Django 5.0.4 on 2026-05-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0024_globalsiteconfig_assignedto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrier',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biometric',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nvr',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
