# Generated by Django 5.0.4 on 2026-05-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0025_barrier_remarks_biometric_remarks_camera_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance'), ('Scrap', 'Scrap')], default='Online', max_length=20),
        ),
    ]
