# Generated by Django 5.0.4 on 2026-05-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0026_alter_camera_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barrier',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance'), ('Scrap', 'Scrap')], default='Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='biometric',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance'), ('Scrap', 'Scrap')], default='Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='networkswitch',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance'), ('Scrap', 'Scrap')], default='Online', max_length=20),
        ),
        migrations.AlterField(
            model_name='nvr',
            name='status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Maintenance', 'Maintenance'), ('Scrap', 'Scrap')], default='Online', max_length=20),
        ),
    ]
