# Generated by Django 5.0.4 on 2026-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0028_rack_rackrelocation_rackremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='nvr',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
