# Generated by Django 5.0.4 on 2026-05-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0029_nvr_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometric',
            name='macAddress',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
