# Generated by Django 5.0.4 on 2026-05-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0030_biometric_macaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('occupation_type', models.CharField(choices=[('College', 'College'), ('IT Company', 'IT Company')], max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
