# Generated by Django 5.0.4 on 2026-05-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0031_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='occupation_type',
            field=models.CharField(max_length=50),
        ),
    ]
