# Generated by Django 5.0.4 on 2026-05-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0032_alter_occupation_occupation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupation',
            name='merged_from',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
