# Generated by Django 5.0.4 on 2026-06-08 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0034_brand_remove_nvr_sno_biometric_gateway_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nvr',
            name='sNo',
        ),
    ]
