# Generated by Django 6.0.5 on 2026-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0036_nvr_portnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometric',
            name='usage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
