# Generated by Django 6.0.5 on 2026-06-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0037_biometric_usage_camera_portnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='portNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
