# Generated by Django 6.0.5 on 2026-06-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0038_camera_portnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('division_type', models.CharField(max_length=50)),
                ('merged_from', models.JSONField(blank=True, default=list)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
    ]
