# Generated by Django 6.0.5 on 2026-06-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0039_division_delete_occupation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barrier',
            old_name='collegeName',
            new_name='divisionName',
        ),
        migrations.RenameField(
            model_name='biometric',
            old_name='collegeName',
            new_name='divisionName',
        ),
        migrations.RenameField(
            model_name='camera',
            old_name='collegeName',
            new_name='divisionName',
        ),
        migrations.RenameField(
            model_name='globalsiteconfig',
            old_name='collegeName',
            new_name='divisionName',
        ),
        migrations.RenameField(
            model_name='masterlocation',
            old_name='collegeName',
            new_name='divisionName',
        ),
        migrations.RenameField(
            model_name='networkswitch',
            old_name='collegeName',
            new_name='divisionName',
        ),
        migrations.RenameField(
            model_name='nvr',
            old_name='collegeName',
            new_name='divisionName',
        ),
        migrations.RenameField(
            model_name='rack',
            old_name='collegeName',
            new_name='divisionName',
        ),
        migrations.AlterUniqueTogether(
            name='masterlocation',
            unique_together={('divisionName', 'block', 'floor', 'room')},
        ),
    ]
