# Generated by Django 6.0.5 on 2026-06-17 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0042_alter_block_id_alter_floor_id_alter_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='cctv.block'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='floor',
            unique_together={('name', 'block')},
        ),
    ]
