# Generated by Django 6.0.5 on 2026-06-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0043_floor_block_alter_floor_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MasterLocation',
        ),
    ]
