# Generated by Django 6.0.5 on 2026-06-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0044_delete_masterlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkswitch',
            name='ethUplink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='networkswitch',
            name='sfpUplink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
