# Generated by Django 5.0.4 on 2026-06-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0045_networkswitch_ethuplink_networkswitch_sfpuplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometric',
            name='hardwareSerial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='camera',
                    name='model',
                    field=models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            database_operations=[]
        ),
    ]
