# Generated by Django 5.0.4 on 2026-04-29 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cctv', '0001_initial'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignedTo',
            field=models.ForeignKey(blank=True, db_column='assignedTo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cameraId',
            field=models.ForeignKey(db_column='cameraId', on_delete=django.db.models.deletion.CASCADE, to='cctv.camera'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='raisedBy',
            field=models.ForeignKey(db_column='raisedBy', on_delete=django.db.models.deletion.CASCADE, related_name='raised_tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
