# Generated by Django 5.0.4 on 2026-04-30 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cctv', '0005_camera_campuszone'),
        ('maintenance', '0003_project_ticket_projectid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cameraId',
            field=models.ForeignKey(blank=True, db_column='cameraId', null=True, on_delete=django.db.models.deletion.CASCADE, to='cctv.camera'),
        ),
    ]
