# Generated by Django 5.0.4 on 2026-05-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_ticket_actiontaken_ticket_category_ticket_endtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='serviceImage',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/service_images/'),
        ),
    ]
