# Generated by Django 6.0.5 on 2026-05-12 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_ticket_serviceimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='workImage',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/work_images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='workRemarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
