# Generated by Django 5.0.4 on 2026-05-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_ticket_workimage_ticket_workremarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='block',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='collegeName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='floor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='room',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
