# Generated by Django 5.0.4 on 2026-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_ticket_block_ticket_collegename_ticket_floor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignedStaff',
            field=models.ManyToManyField(blank=True, related_name='tickets', to='maintenance.maintenancestaff'),
        ),
    ]
