# Generated by Django 5.0.4 on 2026-05-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_maintenancestaff_ticket_assignedstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='bill_document',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/projects/bills/'),
        ),
        migrations.AddField(
            model_name='project',
            name='bill_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='po_document',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/projects/pos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bill_document',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/tickets/bills/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='bill_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='po_document',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/tickets/pos/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
