# Generated by Django 5.0.4 on 2026-06-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_ticketdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completedDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='completedImage',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/completed_images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='completedTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='createdDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='createdImage',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/created_images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='createdTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='inProgressDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='inProgressImage',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/inprogress_images/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='inProgressTime',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]

