# Generated by Django 6.0.5 on 2026-06-09 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_ticket_completeddate_ticket_completedimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketCompletedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='maintenance/completed_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_images', to='maintenance.ticket')),
            ],
        ),
    ]
