# Generated by Django 6.0.5 on 2026-06-10 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_ticketremark_image_ticketcompletedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketremark',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/ticket_remarks/'),
        ),
    ]
