# Generated by Django 6.0.5 on 2026-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_ticketremark_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralBillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('bill_number', models.CharField(blank=True, max_length=255, null=True)),
                ('po_number', models.CharField(blank=True, max_length=255, null=True)),
                ('ps_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_document', models.FileField(blank=True, null=True, upload_to='maintenance/general/bills/')),
                ('po_document', models.FileField(blank=True, null=True, upload_to='maintenance/general/pos/')),
                ('ps_document', models.FileField(blank=True, null=True, upload_to='maintenance/general/ps/')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
