# Generated by Django 6.0.5 on 2026-06-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_generalbillinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalbillinginfo',
            old_name='po_number',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='generalbillinginfo',
            old_name='ps_number',
            new_name='area_budget',
        ),
        migrations.RenameField(
            model_name='generalbillinginfo',
            old_name='bill_number',
            new_name='bill_no',
        ),
        migrations.RenameField(
            model_name='generalbillinginfo',
            old_name='title',
            new_name='work',
        ),
        migrations.RemoveField(
            model_name='generalbillinginfo',
            name='ps_document',
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='bill_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='handover_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='opex_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='opex_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='opex_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='payment_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='po_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='po_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='pr_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='generalbillinginfo',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
