# Generated by Django 6.0.5 on 2026-06-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_rename_po_number_generalbillinginfo_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='collegeName',
            new_name='divisionName',
        ),
    ]
