# Generated by Django 6.0.5 on 2026-06-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_rename_collegename_ticket_divisionname'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='instructionBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
