# Generated by Django 6.0.5 on 2026-06-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_project_instructionby'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancestaff',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
