# Generated by Django 6.0.5 on 2026-06-15 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_maintenancestaff_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralBillingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='maintenance/general/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('general_billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='maintenance.generalbillinginfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('Bill', 'Bill'), ('PO', 'PO')], max_length=10)),
                ('number', models.CharField(max_length=255)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='maintenance/projects/billing_records/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='maintenance.project')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('Bill', 'Bill'), ('PO', 'PO')], max_length=10)),
                ('number', models.CharField(max_length=255)),
                ('amount', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='maintenance/tickets/billing_records/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='maintenance.ticket')),
            ],
        ),
    ]
