# Generated by Django 6.0.5 on 2026-06-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_generalbillingdocument_projectbillingrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completedVideo',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/completed_videos/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='createdVideo',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/created_videos/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='inProgressVideo',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/inprogress_videos/'),
        ),
    ]
