# Generated by Django 5.0.4 on 2026-06-30 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_ticket_completedvideo_ticket_createdvideo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='assignedStaff',
        ),
        migrations.DeleteModel(
            name='MaintenanceStaff',
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-createdAt', '-id']},
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='ticket',
                    name='receivedDate',
                    field=models.DateField(blank=True, null=True),
                ),
            ],
            database_operations=[]
        ),
        migrations.AddField(
            model_name='ticket',
            name='assignedStaff',
            field=models.ManyToManyField(blank=True, related_name='tickets_assigned_as_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
