# Generated by Django 5.0.4 on 2026-07-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_delete_maintenancestaff_alter_ticket_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticketDevice',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
