# Generated by Django 5.0.4 on 2026-07-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_ticket_ticketdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='raisedByName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
